### PR TITLE
Update colons to pass SwiftLint

### PR DESCRIPTION
**Pull request by AJ9**
To use SwiftGen in tandem with [SwiftLint](https://github.com/realm/SwiftLint) the colons on `strings-default.stencil`, `storyboards-default.stencil` and `images-default.stencil` need to be updated to remove the prefixing space.

I realise this is a trivial improvement, but will reduce compiler warnings when used with SwiftLint!

storyboard stencil
image stencil

### CODE REVIEW

**Comment by AJ9** [comment]
Should have updated the tests! Doh!

**Comment by AliSoftware** [comment]
I love the idea :heart:

Don't forget to update the other templates (not only the "defaults" ones) too.

Note that you can push new commits to your master branch and they will be added to this Pull Request automatically: no need for a new PR, you can still use this one (and reopen it when ready)

**Comment by AJ9** [comment]
I'll get it done :) and reopen

**Comment by AliSoftware** [comment]
Cool thx :+1:

And happy new year! :tada:

**Comment by AJ9** [comment]
Recreated this pull request after Master was updated, rebased and unit tests now pass #79

**Pull request closed without merging**
