### PR TITLE
Fixed typos: 'instanciate' -> 'instantiate'

### PR DESCRIPTION
**Pull request by pankolega**
'nuff said :)

### CODE REVIEW

**Comment by darecki** [comment]
Great idea! That typo was bothering me very much.

**Comment by AliSoftware** [comment]
Damn, that's one of those words I'll misspell every time due to the different spelling of the same word in French :laughing: Well spotted, sir, thx!

**Comment by AliSoftware** [comment]
Could you just maybe add an entry in the `CHANGELOG.md` to credit yourself and make note that the `storyboards-default` template changed?

It may seem like a very little change, but every change deserve attribution, and as a lot of people probably use the default template this will change their generated code and will have to adapt their codebase, so it's worth mentioning anyway imho.

**Comment by pankolega** [comment]
Sure thing. It is definitely a breaking change.

**Comment by AliSoftware** [comment]
Sorry I should have been more explicit: version `0.7.5` is already released to Homebrew, without that change. So the entry in the changelog should be in a new `## Master` entry, ready for the next release 
(which will probably be 0.7.6, but we don't know yet, as I might wait for some other issues to be fixed before releasing a new version and those new issues might deserve a `0.8.0`, idk yet)

**Comment by pankolega** [comment]
That's right. I didn't want to do that without your explicit instruction.

**Comment by AliSoftware** [comment]
Perfect :ok_hand:  thx for your contribution @pankolega !

**Comment by phatblat** [comment]
Yay! Was just about to create a PR for this. English is weird. :confused:

**Pull request merged**
