### PR TITLE
Add core data commands

### PR DESCRIPTION
**Pull request by Igor-Palaguta**
https://github.com/AliSoftware/SwiftGen/issues/185

Added [motoswift](https://github.com/Igor-Palaguta/MotoSwift) commands to swiftgen 

Done:
1) New commands
2) Core Data xcdatamodel/xcdatamodeld parsers
3) stencil templates that works similar to XCode and Mogenerator
4) Tests

TODO:
1) documentation, readme

@AliSoftware please review

### CODE REVIEW

**Comment by Igor-Palaguta** [comment]
Example of commands with default arguments
```
swiftgen coredata human TypesModel.xcdatamodeld
swiftgen coredata machine TypesModel.xcdatamodeld
swiftgen coredata model TypesModel.xcdatamodeld
```

With defined arguments
```
swiftgen coredata human --output "./Human" --file-mask "{{class}}.swift" --template mogenerator TypesModel.xcdatamodeld
swiftgen coredata machine --output "./Machine" --file-mask "_{{class}}.swift" --template mogenerator TypesModel.xcdatamodeld
swiftgen coredata model --output Model.swift --enumName Model TypesModel.xcdatamodeld
```

[TypesModel.xcdatamodeld.zip](https://github.com/AliSoftware/SwiftGen/files/561356/TypesModel.xcdatamodeld.zip)

**Comment by Igor-Palaguta** [comment]
Hello, @AliSoftware 

By mistake merged all your new changes to this branch. Please can you assist what is better to do?

All other steps I did, you can check them

[ ] rebase that PR and fix the conflicts (they are mainly caused by the recent release of a 3.0.1 version)
[x] ensure your code is written with Swift 2.3 and it still works with Xcode 8, now that SwiftGen 3.0.1 has migrated to these versions
[x] Add documentation & update README.md
[x] Update documentation/Templates.md with the new StencilContext
[x] Maybe also add a playground page demonstrating that new command?
[x] Add an entry in the CHANGELOG to credit yourself

**Comment by AliSoftware** [comment]
Not sure I see where you merged my changes into your branch (instead of rebasing?), at least I don't see it from GitHub. But if you did, you could git reset to the commit before the merge and start again from that.

**Comment by Igor-Palaguta** [comment]
moved all changes to https://github.com/AliSoftware/SwiftGen/pull/195 please review

**Comment by Igor-Palaguta** [comment]
Hello @AliSoftware please check https://github.com/AliSoftware/SwiftGen/pull/195

**Pull request closed without merging**
