### PR TITLE
Add Swift3 Templates 

### PR DESCRIPTION
**Pull request by AndrewSB**
related to #116

### CODE REVIEW

**Comment by AndrewSB** [comment]
@AliSoftware it would be awesome if this could be bundled into a release 😄

**Comment by AliSoftware** [comment]
If you want those to be bundled I'd appreciate some unit tests to ensure what they generate is always what you expect (duplicate and adapt an existing test case)

Also please add an entry in the CHANGELOG to credit yourself :wink:

**Comment by AndrewSB** [comment]
updated 👍

**Comment by AliSoftware** [comment]
@AndrewSB I tried restarting the Travis build but it seems to fail every time, crashing Xcode while running tests. Could you take a look to try and fix it before I consider merging?

**Comment by AndrewSB** [comment]
Will do! Sorry for not testing locally before updating the PR

**Comment by AndrewSB** [comment]
Tests pass locally! Should be ready to merge 🙃

**Comment by AndrewSB** [comment]
^ rebased

**Pull request merged**
