### PR TITLE
Fixed an issue with install paths prefixed with ~

### PR DESCRIPTION
**Pull request by jessearmand**
Expand paths for binary, template, and framework.

### CODE REVIEW

**Comment by AliSoftware** [comment]
:+1: cool thanks!!

Did you have the occasion to test it both with `~` and path with spaces then?

**Comment by jessearmand** [comment]
It still have a minor issue with the template directory. I tried to surround it with double quotes, but it generates another directory inside the template dir. 

Which is the 1st word of that template directory with space.

**Comment by jessearmand** [comment]
Ah nevermind, my local templates folder was messed up until I add the surrounding double quotes. After I cleaned up, it's okay.

You can test these changes again. Thanks.

**Comment by AliSoftware** [comment]
Thanks again for the PR, seems :ok_hand: now; merged! :tada:

**Pull request merged**
