### PR TITLE
Feature/adding all values in images enum

### PR DESCRIPTION
**Pull request by GUL-**
Add an array in the images enum so we can iterate over them.

### CODE REVIEW

**Comment by AliSoftware** [comment]
I think that feature is very rarely useful (I never had to iterate over all the images in my Assets Catalog, and don't think most of people do), so I think that'll make the generated file quite long (like when people have 100+ images in their assets catalog)

So here's what I suggest:

1. Keep the existing template unchanged (and revert the examples in README & Playground)
2. Create **a separate template** that adds what you did so we can have this `allValues` entry, but as an opt-in option. People wanting to have this could simply use your template instead of the default one.
3. I'll then include your template alongside mine when SwiftGen is installed. Once #42 is merged, which would allow people to use `--templateName` to specify a template by name instead of by full path, this would make it easier for people to choose the default template without `allValues` or your template with it

**Comment by AliSoftware** [comment]
Merged via d430f568a7cf98abfa58c94b3bf029db2853362d

**Comment by GUL-** [comment]
Thank you very much to accept this MR :-) :+1:

**Comment by AliSoftware** [comment]
Now that #50 is merged, you'll be able to use `swiftgen images -t allvalues PATH` in order to use this specific template which will be bundled with SwiftGen in the next release.

**Pull request closed without merging**
