### PR TITLE
Fix swift 3 renaming compile error

### PR DESCRIPTION
**Pull request by kiliankoe**
`NSLocale.current()` has been renamed to `Locale.current`

### CODE REVIEW

**Comment by AliSoftware** [comment]
Thx! Please add an entry in the CHANGELOG.md to credit yourself too!

**Comment by kiliankoe** [comment]
Done, thanks 😊

**Comment by AliSoftware** [comment]
Very strange, it has been almost a whole day and Travis still haven't started to build and check that PR, wonder what happens… :-/

**Comment by AliSoftware** [comment]
Ah, finally Travis woke up!
It seems you forgot to update the Unit Tests, please add a commit to fix the files in `UnitTests/expected` to match the template change :wink:

**Comment by kiliankoe** [comment]
Ah of course, completely forgot, sorry 😉 Just updated the file.

**Pull request merged**
