### PR TITLE
Add SwiftLint to build script

### PR DESCRIPTION
**Pull request by AJ9**
As discussed in #79 and [here](https://github.com/AliSoftware/SwiftGen/pull/79#issuecomment-168542621), adding SwiftLint as a build script will reduce regression SwiftLint errors. This build script does check the entire SwiftGen project and I've added the following exclusions (to the `.swiftlint.yml` file) with the following reasons:

```
disabled_rules: 
  - force_try
  - force_cast 
  - variable_name 
```

* force_try - Used in some unit tests to create `result` objects
* force_cast - Used [here](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Stencil/SwiftIdentifier.swift#L71) and [here](https://github.com/AliSoftware/SwiftGen/blob/master/SwiftGen.playground/Pages/Storyboards-Demo.xcplaygroundpage/Contents.swift#L56)
* variable_name - Used sensibly [here](https://github.com/AliSoftware/SwiftGen/blob/master/swiftgen-cli/main.swift#L13)

### CODE REVIEW

**Comment by AJ9** [comment]
This does result in 242 issues, maybe we can find a way of just checking the `expected` folder?

**Comment by AliSoftware** [comment]
great work thx!
I think we might get rid of the `try!` calls by replacing them with `guard try? … else { fatalError("some explicit message") }` instead, which would both satisfy SwiftLint and make better error messages, as [I hate killing ponies](http://alisoftware.github.io/swift/2015/09/06/thinking-in-swift-1/) :wink:

**Comment by AliSoftware** [comment]
> This does result in 242 issues, maybe we can find a way of just checking the expected folder?

You can use `swiftlint lint --path …/expected` for that.

The main concern is indeed to ensure the code _generated_ by SwiftGen match SwiftLint styling rules, so the `expected` folder is indeed the most important one to check. But it would be cool to make the codebase of SwiftLint itself cleaner by addressing those 242 warnings too.

I think we could use `swiftlint lint --strict --path …/path/to/expected` in the `.travis.yml` file, so that Continuous Integration only check for `expected` folder, but fail even on warning (`--strict`).

And then use `swiftlint` in the Script Build Phase to check the whole codebase (and not just expected) but only warn and not fail, and (later?) address those lint warnings in the SwiftGen codebase itself.

**Comment by AliSoftware** [comment]
I just realized a problem: `swiftlint` won't be able to lint the files in `UnitTests/expected` because those files have the `.swift.out` extension, not just `.swift`, so they are discarded by SwiftLint and not analyzed. SwiftLint only analyze files having the `.swift` extension.

So I'm not sure there is a proper way to validate that the templates or their output does not violate SwiftLint rules. Maybe there is hope with the `swiftlint lint --use-stdin` somehow, but not with `swiftlint` directly analyzing the files.

**Comment by AliSoftware** [comment]
Hi @AJ9 

I finally took the time to merge this. In fact I reintegrated SwiftLint the way you started to do it (but in my own branch to start anew since your branch started to be a bit behind the latest merged PRs), and in addition I added linting for both the templates and the SwiftGen code itself, and fixed all the warnings & errors generated by the listing.

Thanks again for taking a stab at it!

**Pull request closed without merging**
