### PR TITLE
Issue 61

### LINKED ISSUE #61: Add View Controller placeholders support
XCode 7 and iOS 9 supports View Controller placeholders in your storyboards. But swiftgen doesn't support them.

Generated enum looks like this:

enum ServicePromo : String, StoryboardScene {
      case nextSegue = "NextSegue"
      static func nextSegueViewController() -> UIViewControllerPlaceholder 
      {
        return ServicePromo.nextSegue.viewController() as! UIViewControllerPlaceholder
      }
}

### PR DESCRIPTION
**Pull request by vkaramov**
Added view controller placeholders support

Fix #61

### CODE REVIEW

**Comment by AliSoftware** [comment]
Could you add the associated Unit Tests please, to ensure this work as expected and doesn't break in the future?

**Comment by AliSoftware** [comment]
Could you rebase the branch against master so the CI can test it and the merge can take place without any conflict?

**Comment by vkaramov** [comment]
Done.

**Comment by AliSoftware** [comment]
Errr… doesn't seem like you rebased on top of master (which is currently commit 61a1cbe51f5470891c7b429b1853bd4b2176cb13)

Could you make sure you pulled the latest `master` before rebasing your branch?

* `git checkout master`
* `git pull origin master`
* `git checkout issue_61`
* `git rebase master`
* `git push`

**Comment by vkaramov** [comment]
What origin do you mean? My fork's origin is named origin, but yours is upstream.

**Comment by AliSoftware** [comment]
Ah yeah sorry, then replace the `origin` with `upstream` in the commands I gave above, you're right.

The idea is to get all the commits from my fork (`upstream` then) in your `master` branch to ensure your `master` is up-to-date with mine, then rebase (~ detach and reattach) your branch `issue_61` on top of this updated `master` branch and push it to your fork.

**Comment by vkaramov** [comment]
I had to force-push to make it work.

**Comment by AliSoftware** [comment]
Yeah that normal, perfect then! Thanks and sorry for the trouble, will be able to look into it properly now :+1:

**Comment by AliSoftware** [comment]
Merged via 8c49321b4d3df54264986429641d3a837f021dfb

Thanks a lot for this PR @vkaramov (and sorry this took so long)!

**Pull request closed without merging**
