### PR TITLE
Images templates for OS X

### PR DESCRIPTION
**Pull request by tbaranes**
Here the first templates (and their tests) for OS X: Images
I tested the template in my own project, it seems to be working without any issues!

I didn't update the README, since the usage doesn't change, not sure what we should add, maybe a note? Also, the same localizable templates for iOS can be reused for OS X, nothing to change. 

#101 🎉

### CODE REVIEW

**Comment by AliSoftware** [comment]
Super cool, thanks!! Will look at it soon but seems ace! 👍

**Comment by tbaranes** [comment]
When I wake up this morning, I got an idea and can't get away from it, I have to do it! Here a nicer way to handle Images for OS X: don't duplicate any templates (that was the easiest way), reuse the same templates, and the same tests for both since the output difference is just a type:

```swift
#if os(iOS)
  import UIKit.Image
  typealias Image = Image
#elseif os(OSX)
  import AppKit.NSImage
  typealias Image = NSImage
#endif
```

**Comment by AliSoftware** [comment]
Ohhh indeed great idea! :100:!

**Comment by AliSoftware** [comment]
Hey @tbaranes 

To thank you for your work on these latest PRs and also in an effort to follow the same rules as [Moya's Contributors Guidelines](https://github.com/Moya/contributors), I've added you as a collaborator on SwiftGen.
That doesn't mean any special expectation from you, it just gives you the possibility now to review PRs and Issues and merge PRs yourself and contribute more easily to SwiftGen in the future if you ever want to.

Thx 👍

**Comment by tbaranes** [comment]
Thanks for the invitation!

**Pull request merged**
