### PR TITLE
Migrate Swift 3 templates to use lowercase enums

### PR DESCRIPTION
**Pull request by AliSoftware**
@Sajjon could you test this in your Swift 3 project and check all the templates work and generate expected code that compiles properly? Thx!

### CODE REVIEW

**Comment by Sajjon** [comment]
Sorry @AliSoftware ! So writing here now, as I said, got installation error after `rake install`, what am I missing?

https://github.com/AliSoftware/SwiftGen/issues/116#issuecomment-244602188

**Comment by AliSoftware** [comment]
The error you got when trying to `rake install` doesn't seem to be related to PathKit itself. It more seems to be related to `xcodebuild` not finding any suitable Simulator to run the tests. It happens the first dependency it tries to build to run those tests is PathKit that's why you see that it failed why building it at the end, but higher in the log you see it's because of the simulator missing.

**Comment by AliSoftware** [comment]
fwiw, got the same error why running the Rakefile too. Probably something changed in Xcode 8 build process? Seems very strange. Still investigating rn

**Comment by Sajjon** [comment]
@AliSoftware yes it is actually the exact same error I got a couple of days ago when trying to perform a `pod lib lint` in order to create a cocoapods of [my SwiftReflection project](https://github.com/Sajjon/SwiftReflection). So yes this seems to be an Xcode 8 related problem.

But isn't it strange, because I thought the version of `xcbuild` could be selected with `xcode-select`, when I do:
```
in SwiftGen/ on master 
› sudo xcode-select -switch /Applications/Xcode-beta.app
Password:

in SwiftGen/ on master 
› rake install                                          
rake aborted!

[!!!] You need to use Xcode 7.x to compile SwiftGen. Use xcode-select to change the Xcode used to build from command line.

/Users/alge/Developer/iOS/SwiftGen/Rakefile:46:in `block in <top (required)>'
Tasks: TOP => install => install:light => build => check_xcode_version
(See full trace by running task with --trace)
```
I get this message: **You need to use Xcode 7.x to compile SwiftGen**.

But anyway it failes with non beta, selected. How come it fails just because Xcode 8 is installed, but not specified with `xcode-select`

 Maybe we can try enable building with Xcode 8?

**Comment by AliSoftware** [comment]
Yes, the code of SwiftGen itself hasn't been updated to Swift 3 yet (the tool itself is written in Swift 2), so SwiftGen still needs to be compiled with Xcode 7 for now and isn't to be compiled with Xcode 8.

_(I plan to make a big migration soon after my busy September month)_

Btw after relaunching `rake install` I managed to build SwiftGen correctly. Could you re-select Xcode 7 and retry `rake install`? It seems that ones it created the missing simulator on the first failed build it manages to build the second time.

**Comment by AliSoftware** [comment]
I've zipped a compiled version if you still have trouble building SwiftGen from source.
[swiftgen-3.0.0.zip](https://github.com/AliSoftware/SwiftGen/files/453943/swiftgen-3.0.0.zip)

Note: it's tagged "3.0.0" as I soon plan do a release with that version number, but the future actual 3.0.0 might be different so you should unzip it somewhere where you could easily delete it later to avoid messing with the versions when you'll update to the actual 3.0.0 later.
You could for example unzip it on your Desktop, and invoke SwiftGen using the full path to it like `~/Desktop/swiftgen-3.0.0/bin/swiftgen`

**Comment by Sajjon** [comment]
@AliSoftware You are absolutely right! Running `rake install` a second time worked, but I downloaded and used your zipped version anyway, thanks! 

Now SwiftGen generates lowercase Enums, so that part is great! Also a get `Locale.current`instead of `NSLocale.current()`, however it does not compile because every LocalizedString taking arguments `%@`fails. 

`Enum case <ENUM_TAKING_ARGUMENT> not found in type L10n`, lets call `<ENUM_TAKING_ARGUMENT>` **yourNameString**. The case **yourNameString** is present in the Enum as:
```swift
case .yourNameString(String)
``` 

But still when used in the computed property `var string: String` inside the `extension L10n: CustomStringLiteral` like this:
```swift
case .yourNameString(let p0):
```

It does not compile.

Any idea? 😁

**Comment by AliSoftware** [comment]
I'm not sure I understand what you're saying. You mean the `case` generated inside the enum is actually generated like

```swift
enum L10n {
…
  case .yourNameString(String)
…
}
```

Instead of being this, with no leading dot?

```swift
enum L10n {
…
  case yourNameString(String)
…
}
```

Or was it a typo in your comment? And if so, what is the exact actual error? Could you give me the real example of your `Localizable.strings` line and what is generated from it?

Because if I copy the content of the`Strings-File-Swift3.swift.out` file from my unit test fixtures in Xcode 8b6 it seems to compile, while this fixture has strings with `%@` and cases with `String` associated types, so I'm not sure I see what you're saying?

**Comment by Sajjon** [comment]
@AliSoftware sorry it was a typo! I updated it now. I am saying that all the strings `Localizable.strings` containing `%@` and `%d` i.e. taking parameters are generating cases in L10n that fails to compile.

**Comment by AliSoftware** [comment]
Yes ok but what's the actual error you got in Xcode when the compilation fails?
And could you give an example of the generated code that fails to compile?

Because I can't reproduce it on my end so wondering what's different in your project.

**Comment by AliSoftware** [comment]
e.g. this is what is generated by the Unit Tests, and if I copy/paste that into a playground in Xcode 8 b6 then it compiles and works?!

<details>
<summary>Code generated by `swiftgen strings -t swift3`</summary>

```swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum L10n {
  /// Title of the alert
  case alertTitle
  /// Some alert body there
  case alertMessage
  /// Hello, my name is %@ and I'm %d
  case greetings(String, Int)
  /// You have %d apples
  case applesCount(Int)
  /// Those %d bananas belong to %@.
  case bananasOwner(Int, String)
  /// These are %3$@'s %1$d %2$@.
  case objectOwnership(Int, String, String)
  /// Settings
  case settingsNavigationBarTitleEvenDeeper
  /// User Profile Settings
  case settingsUserProfileSectionHeaderTitle
  /// Here you can change some user profile settings.
  case settingsUserProfileSectionFooterText
  /// DeepSettings
  case settingsNavigationBarTitleEvenDeeperThanWeCanHandle
}
// swiftlint:enable type_body_length

extension L10n: CustomStringConvertible {
  var description: String { return self.string }

  var string: String {
    switch self {
    case .alertTitle:
      return L10n.tr(key: "alert_title")
    case .alertMessage:
      return L10n.tr(key: "alert_message")
    case .greetings(let p0, let p1):
      return L10n.tr(key: "greetings", p0, p1)
    case .applesCount(let p0):
      return L10n.tr(key: "apples.count", p0)
    case .bananasOwner(let p0, let p1):
      return L10n.tr(key: "bananas.owner", p0, p1)
    case .objectOwnership(let p0, let p1, let p2):
      return L10n.tr(key: "object.ownership", p0, p1, p2)
    case .settingsNavigationBarTitleEvenDeeper:
      return L10n.tr(key: "settings.navigation-bar.title.even.deeper")
    case .settingsUserProfileSectionHeaderTitle:
      return L10n.tr(key: "SETTINGS.USER_PROFILE_SECTION.HEADER_TITLE")
    case .settingsUserProfileSectionFooterText:
      return L10n.tr(key: "seTTings.uSer-proFile-sectioN.footer_text")
    case .settingsNavigationBarTitleEvenDeeperThanWeCanHandle:
      return L10n.tr(key: "settings.navigation-bar.title.even.deeper.than.we.can.handle")
    }
  }

  private static func tr(key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}

func tr(key: L10n) -> String {
  return key.string
}

let s = tr(key: .settingsNavigationBarTitleEvenDeeper)
print(s)
```
</details>

**Comment by Sajjon** [comment]
I will create a mimimum project for you, hold on a sec!

**Comment by Sajjon** [comment]
[Using SwiftGen in the Zip you linked to](https://github.com/AliSoftware/SwiftGen/files/453943/swiftgen-3.0.0.zip) running this command in the terminal:

```bash
./swiftgen-3.0.0/bin/swiftgen strings -t swift3 --output NotCompiling/Enums/Generated/Strings.swift NotCompiling/Localizable.strings
File written: NotCompiling/Enums/Generated/Strings.swift
```

Generates this file:

```swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum L10n {
  /// Your name is %@
  case yourname(String)
}
// swiftlint:enable type_body_length

extension L10n: CustomStringConvertible {
  var description: String { return self.string }

  var string: String {
    switch self {
      case .yourName(let p0):
        return L10n.tr(key: "YourName", p0)
    }
  }

  private static func tr(key: String, _ args: CVarArg...) -> String {
    let format = NSLocalizedString(key, comment: "")
    return String(format: format, locale: Locale.current, arguments: args)
  }
}

func tr(key: L10n) -> String {
  return key.string
}

```

You can find the file [here, in this example project on my Github page](https://github.com/Sajjon/SwiftGen3Error/blob/master/NotCompiling/Enums/Generated/Strings.swift)

**Comment by Sajjon** [comment]
@AliSoftware please let me know if you get the same result! And if I can do anything to help!

**Comment by AliSoftware** [comment]
Ah with the code extract your posted in your comment above that's now obvious why that doesn't compile, that's just the extract I was missing:

* In the enum the case is named `case yourname(String)` (all lowercased)
* In the `extension` and `switch` it's named `case .yourName(let p0):` (camelCased)

That's why it fail to compile, it's because it doesn't match.

If I look at the template I indeed forgot to add a `|lowercase` filter in the specific case when you have params (you can see in [this diff](https://github.com/AliSoftware/SwiftGen/pull/166/files#diff-03d9f4838eb2eaae65ac99f542b448e3L23) that the cases for `{% if string.params %}` and `{% else %}` cases are not using the same filters on `{{string.key|…filters…}}`)

**Comment by Sajjon** [comment]
I right, stupid me missed that! So download from master again and then recompile? 😄

**Comment by Sajjon** [comment]
@AliSoftware are you lower-casing the whole enum or camelcasing the enum but with leading lowercase. It would be nice if it would be camelcased with leading lowercase! 👍

**Comment by AliSoftware** [comment]
Yeah just wait until I pushed a fix. The fix is easy but given my unit tests missed that case I'm currently adding a unit test for that use case to be sure to catch it properly. Will let you know when the fix is on master ;)

**Comment by AliSoftware** [comment]
I'm doing lowerCamelCased.

**Comment by AliSoftware** [comment]
Ok, applied a fix. @Sajjon if you could pull from master and re-test that would be great 👍 

---

Note that this made me realize that it wasn't easy to please every people's conventions (after all, that's why SwiftGen is based on templates, so everybody can adjust the templates to fit their own conventions, but still providing good defaults is sometimes hard).
Because applying correct filters so that `"YourName"` generates `case yourName` and not `case your name` means that people using all-caps conventions like `"YOUR_NAME"` in their `Localizable.strings` file rather than `"YourName"` will end up with `case yourname` and not `case yourName`.

it's very hard to convert snake case to camel case but still keep the original case, but lower the first word. The last example `"YOUR_NAME"` would generate `case yourname` all lowercased because my filter to lowercase doesn't only lowercase the first letter, but the first "word", so that `"URL_home"` is transformed in `urlHome` and not `uRLHome`… so it's hard to handled every possible use case perfectly!

I've chosen to ignore the case where people write their keys in all caps (they'll end up generating `case yourname` for key `"YOUR_NAME"`) because that's probably the less frequent solution. That doesn't mean nobody use that convention for their string keys, but you can't please everybody and every convention out there, and they can totally duplicate the template to create a custom one if they need that special case.

**Comment by AliSoftware** [comment]
Sorry I meant not rebuild from master, but rebuild from that `feature/swift3` branch, as this PR isn't merged just yet until you confirm me it works ;)

**Comment by Sajjon** [comment]
@AliSoftware Works like a charm, **THANKS A LOT!!!** 🎉

**Comment by Dschee** [comment]
I got errors using this branch and fixed them in 4363072. I hope that's fine with you – it's basically three calls that I changed in the Strings templates to the updated Foundation API.

**Comment by AliSoftware** [comment]
@Dschee why did you update all the templates, including the ones for Swift 2, to the Swift 3 syntax?!

**Comment by Dschee** [comment]
Oh no, seems like I misunderstood this branch. Fixing it, moment please! Sorry!

**Comment by Sajjon** [comment]
@AliSoftware now I am running `swiftgen strings -t swift3` how can I generate swift3 enums with Dot Syntax?

Neither
`swiftgen strings -t swift3 -t dot-syntax`
nor
`swiftgen strings -t swift3 dot-syntax`
worked.

So maybe not possible right now? Do we need a swift3dotsyntax template maybe?

**Comment by Sajjon** [comment]
I have not yet used DotSyntax, but seams neat! And you wrote 

> This is the recommended way of using the strings command in SwiftGen and will replace the current default in future versions

So seams like a good idea ;)

**Comment by Dschee** [comment]
Yup, I have just reset the branch and try to add a template with swift3 support! :)

**Comment by AliSoftware** [comment]
Yeah, SwiftGen being based on templates, the whole point is to let people choose which template they want to use, either the swift 2 or swift 3 templates, instead of forcing everybody to migrate to Swift 3. That's the whole point of being template-based!

* For the moment there's only one `swift3` template for each subcommand (so there's only `strings-swift3.stencil` for the `strings` subcommand) where there are already multiple templates for Swift 2. 

* In the future I hope people add more Swift3-compatible templates, like duplicating `strings-dotsyntax.stencil` into `strings-swift3dotsyntax.stencil` for example, so that we could indeed use this template (via `-t swift3dotsyntax`) to have the dot syntax for Swift 3 too.

But a lot of people are waiting for this 3.0.0 version and I've been postponing this 3.0.0 release way too much now, so I think it's time to release 3.0.0 now before continuing adding stuff and postponing it again.

Feel free to open a new PR _after_ I released 3.0.0 to add other Swift 3 template, especially porting the `dot syntax` template into a `swift3dotsyntax` one*, so that we can integrate it in a 3.1.0 or something soon, I'd love that!

---
_* the only problem with the `dotsyntax` and `structured` templates is that they contain heavily copy/pasted portions. I'd love to make it recursive instead, and maybe it's possible, so that would reduce the template code a lot and make it easier to change stuff in it like porting it to Swift 3, but I haven't had enough time to look into it. If someone is interested, feel free to try: I think with Stencil's `{% include %} or `{% set %}` tags, one can probably achieve some recursivity somewhere in there_

**Comment by Dschee** [comment]
I added support for dot-syntax and Swift 3. If you haven't released yet, could you put it in?

**Comment by AliSoftware** [comment]
Oh shoot, that was fast 👍 
@Dschee didn't release yet, but I've closed the branch and the PR already. Could you cherry pick your changes into a brand new branch and create a dedicated PR? Thanks!

**Comment by Dschee** [comment]
Sure, just a moment.

**Comment by Dschee** [comment]
Done, see #167.

**Comment by AliSoftware** [comment]
[Release 3.0.0 waiting to be accepted by Homebrew](https://github.com/Homebrew/homebrew-core/pull/4510)!

Thanks again for your contribution @Sajjon @Dschee ! Now it's open season for all those PRs improving the templates we were talking about for the next 3.x release 🎉

**Pull request merged**
