### PR TITLE
Fix issues #47 and #48

### PR DESCRIPTION
**Pull request by vkaramov**

### CODE REVIEW

**Comment by AliSoftware** [comment]
The Unit tests don't pass anymore, could you fix them first and ensure your changes don't break any of them? Thx

**Comment by AliSoftware** [comment]
Also once you're done, please add an entry in `CHANGELOG.md` to credit your work :wink:

**Comment by vkaramov** [comment]
Done :-)

**Comment by AliSoftware** [comment]
It seems like your PR wasn't done on top of the latest commit (especially it doesn't contain the changes done by the latest merged PR).

Could you simply rebase your branch on top of the current master please? Thx

**Comment by vkaramov** [comment]
I've rebased my fixes on top of my current master branch.

**Comment by AliSoftware** [comment]
Ok strange then, why does GitHub still says it has conflicts? :hushed:

**Comment by vkaramov** [comment]
Actually I forgot. Now I'm pulled your master, but it still produces conflicts.

**Comment by AliSoftware** [comment]
Doesn't seem like you rebased and pushed back the rebased branch on GitHub then?

**Comment by vkaramov** [comment]
Yes

**Comment by AliSoftware** [comment]
You probably didn't push on your `issue_47_48` branch on GitHub, because the rebased commit is not visible on GitHub at all :-/

**Comment by vkaramov** [comment]
You mean I should rebase your master on top of my issue_47_48 branch? I just did it.

**Comment by AliSoftware** [comment]
I mean you should rebase your `issue_47_48` branch on top of my master, then force-push the rebased branch to GitHub so I can see the rebased branch instead of the original. Once you force-pushed your rebased `issue_47_48` branch, we should see the rewritten commits in this PR below the comments and the conflicts should be gone.

**Comment by vkaramov** [comment]
I don't have write access to **your* master.

**Comment by AliSoftware** [comment]
I'm not saying to push to my master, I'm saying to force-push to your GitHub on your `issue_47_48` branch

**Comment by AliSoftware** [comment]
```bash
# If not done already, make sure sure master is up to date and has all the commits my master branch has
$ git checkout master # to make your working copy be on your local master branch
$ git pull https://github.com/AliSoftware/SwiftGen.git master # to retrieve latest commits from my master on your local master

# Then rebase your issue_47_48 branch on top of your local master
$ git checkout issue_47_48 # make your working copy be on your issue_47_48 local branch
$ git rebase master # rebase that branch on top of your local master (which is now up-to-date with my recent commits)

# Now that your branch is rebased, you can push it all to your GitHub
$ git push --force
```

**Comment by vkaramov** [comment]
Done

**Comment by AliSoftware** [comment]
Ok, still doesn't work, it seems that you rebased (= rewrote) my commits of my master in addition to yours, instead of pulling mine unchanged and rebase only yours.

Don't bother, it seems you won't be able to make it work so I'll merge manually, that would be quicker.

Thanks for the effort though!

**Comment by AliSoftware** [comment]
Closed via 25c383f17a56e2a25730cb53fb3f897d10eecaf2 & 91659afba9f49df598e05a8efd388125dcc34825, made the template opt-in instead of default in 15bf0a139638863d9efe5c5e3f3feee13b7ff30e

**Pull request closed without merging**
